name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run tests
      run: |
        python -m unittest ExperimentTests.py

  deployment:
    enviroment: production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  
      - name: Deploy to S3
        run: |
         aws s3 sync . s3://tyc.bit2bitest.com --delete
      - name: Set Deployment Status
        run: |
          # Obtén el ID del despliegue
          DEPLOYMENT_ID=${{ github.event.deployment.id }}
          echo "Deployment ID: $DEPLOYMENT_ID"

          # Usa el ID del despliegue para actualizar el estado
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses" \
            -d '{"state":"success","log_url":"https://s3.amazonaws.com/tyc.bit2bitest.com/index.html","description":"Deployment finished successfully."}'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
